export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        serif: ["Libre Baskerville", "serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"]
      },
      colors: {
        "ink": "#f8fafc",
        "paper": "#0f172a",
        "seal": "#10b981",
        "mist": "#1e293b",
        
        "inverse-primary": "#064e3b",
        "primary": "#10b981",
        "tertiary-fixed": "#065f46",
        "surface-container-highest": "#334155",
        "on-primary-fixed": "#ecfdf5",
        "tertiary-container": "#047857",
        "surface": "#0f172a",
        "surface-dim": "#020617",
        "surface-container-lowest": "#000000",
        "error-container": "#7f1d1d",
        "on-secondary-fixed": "#ecfdf5",
        "on-secondary-fixed-variant": "#d1fae5",
        "on-surface-variant": "#94a3b8",
        "secondary-container": "#065f46",
        "primary-fixed": "#047857",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#059669",
        "on-background": "#f8fafc",
        "inverse-surface": "#f1f5f9",
        "secondary-fixed": "#0f766e",
        "tertiary": "#10b981",
        "on-surface": "#f8fafc",
        "on-primary-container": "#ecfdf5",
        "primary-container": "#059669",
        "error": "#ef4444",
        "surface-variant": "#1e293b",
        "surface-tint": "#10b981",
        "outline-variant": "#334155",
        "inverse-on-surface": "#0f172a",
        "secondary-fixed-dim": "#14b8a6",
        "surface-container-low": "#1e293b",
        "on-primary": "#0f172a",
        "on-tertiary": "#0f172a",
        "on-tertiary-container": "#ecfdf5",
        "tertiary-fixed-dim": "#34d399",
        "surface-container": "#334155",
        "on-secondary-container": "#ecfdf5",
        "surface-bright": "#1e293b",
        "outline": "#64748b",
        "on-tertiary-fixed-variant": "#ecfdf5",
        "on-error-container": "#fecaca",
        "on-secondary": "#0f172a",
        "surface-container-high": "#475569",
        "on-primary-fixed-variant": "#d1fae5",
        "background": "#0f172a",
        "secondary": "#10b981",
        "on-tertiary-fixed": "#ffffff"
      }
    },
  },
  plugins: [],
}
