/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as merkleCredentialVerifierSol from './MerkleCredentialVerifier.sol/index.js';
export { CredentialVerifier__factory } from './CredentialVerifier__factory.js';