/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CredentialVerifierInterface extends Interface {
    getFunction(nameOrSignature: "getCredential" | "getStudentCredentials" | "issueCredential" | "revokeCredential" | "totalCredentials" | "universityAddress" | "verifyCredential"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CredentialIssued" | "CredentialRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'getCredential', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getStudentCredentials', values: [string]): string;
encodeFunctionData(functionFragment: 'issueCredential', values: [string, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'revokeCredential', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalCredentials', values?: undefined): string;
encodeFunctionData(functionFragment: 'universityAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyCredential', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStudentCredentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalCredentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'universityAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCredential', data: BytesLike): Result;
  }

  
    export namespace CredentialIssuedEvent {
      export type InputTuple = [credentialHash: BytesLike, studentDid: string, issuedBy: AddressLike, ipfsCid: string, issuedAt: BigNumberish];
      export type OutputTuple = [credentialHash: string, studentDid: string, issuedBy: string, ipfsCid: string, issuedAt: bigint];
      export interface OutputObject {credentialHash: string, studentDid: string, issuedBy: string, ipfsCid: string, issuedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialRevokedEvent {
      export type InputTuple = [credentialHash: BytesLike, revokedBy: AddressLike, revokedAt: BigNumberish];
      export type OutputTuple = [credentialHash: string, revokedBy: string, revokedAt: bigint];
      export interface OutputObject {credentialHash: string, revokedBy: string, revokedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CredentialVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): CredentialVerifier;
    waitForDeployment(): Promise<this>;

    interface: CredentialVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCredential: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, string, string, bigint, boolean, boolean] & {studentDid: string, ipfsCid: string, issuedBy: string, issuedAt: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >
    

    
    getStudentCredentials: TypedContractMethod<
      [studentDid: string, ],
      [string[]],
      'view'
    >
    

    
    issueCredential: TypedContractMethod<
      [studentDid: string, credentialHash: BytesLike, ipfsCid: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeCredential: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalCredentials: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    universityAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyCredential: TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[boolean, boolean, string, bigint] & {isValid: boolean, isRevoked: boolean, ipfsCid: string, issuedAt: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCredential'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[string, string, string, bigint, boolean, boolean] & {studentDid: string, ipfsCid: string, issuedBy: string, issuedAt: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getStudentCredentials'): TypedContractMethod<
      [studentDid: string, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'issueCredential'): TypedContractMethod<
      [studentDid: string, credentialHash: BytesLike, ipfsCid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeCredential'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalCredentials'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'universityAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyCredential'): TypedContractMethod<
      [credentialHash: BytesLike, ],
      [[boolean, boolean, string, bigint] & {isValid: boolean, isRevoked: boolean, ipfsCid: string, issuedAt: bigint }],
      'view'
    >;

    getEvent(key: 'CredentialIssued'): TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
getEvent(key: 'CredentialRevoked'): TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;

    filters: {
      
      'CredentialIssued(bytes32,string,address,string,uint256)': TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
      CredentialIssued: TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
    

      'CredentialRevoked(bytes32,address,uint256)': TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
      CredentialRevoked: TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
    
    };
  }