/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleCredentialVerifierSol from './MerkleCredentialVerifier.sol/index.js';
export type { merkleCredentialVerifierSol };
export type { CredentialVerifier } from './CredentialVerifier.js';
export * as factories from './factories/index.js';
export { CredentialVerifier__factory } from './factories/CredentialVerifier__factory.js';