/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CredentialVerifierInterface extends Interface {
    getFunction(nameOrSignature: "batchRoots" | "batches" | "commitBatch" | "getBatch" | "getStudentCredentials" | "revokeCredential" | "revokedCredentials" | "totalBatches" | "totalCredentials" | "universityAddress" | "verifyCredential"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchCommitted" | "BatchRevoked" | "CredentialRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'batchRoots', values: [string]): string;
encodeFunctionData(functionFragment: 'batches', values: [string]): string;
encodeFunctionData(functionFragment: 'commitBatch', values: [string, BytesLike, BigNumberish, string[], BigNumberish[], string[]]): string;
encodeFunctionData(functionFragment: 'getBatch', values: [string]): string;
encodeFunctionData(functionFragment: 'getStudentCredentials', values: [string]): string;
encodeFunctionData(functionFragment: 'revokeCredential', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'revokedCredentials', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalBatches', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalCredentials', values?: undefined): string;
encodeFunctionData(functionFragment: 'universityAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyCredential', values: [string, BytesLike, BytesLike[], BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'batchRoots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStudentCredentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokedCredentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBatches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalCredentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'universityAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCredential', data: BytesLike): Result;
  }

  
    export namespace BatchCommittedEvent {
      export type InputTuple = [batchId: string, merkleRoot: BytesLike, credentialCount: BigNumberish, committedBy: AddressLike, committedAt: BigNumberish];
      export type OutputTuple = [batchId: string, merkleRoot: string, credentialCount: bigint, committedBy: string, committedAt: bigint];
      export interface OutputObject {batchId: string, merkleRoot: string, credentialCount: bigint, committedBy: string, committedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRevokedEvent {
      export type InputTuple = [batchId: string, revokedBy: AddressLike];
      export type OutputTuple = [batchId: string, revokedBy: string];
      export interface OutputObject {batchId: string, revokedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialRevokedEvent {
      export type InputTuple = [credentialHash: BytesLike, batchId: string, revokedBy: AddressLike];
      export type OutputTuple = [credentialHash: string, batchId: string, revokedBy: string];
      export interface OutputObject {credentialHash: string, batchId: string, revokedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CredentialVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): CredentialVerifier;
    waitForDeployment(): Promise<this>;

    interface: CredentialVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batchRoots: TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >
    

    
    batches: TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, bigint, boolean, boolean] & {merkleRoot: string, credentialCount: bigint, committedAt: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >
    

    
    commitBatch: TypedContractMethod<
      [batchId: string, merkleRoot: BytesLike, credentialCount: BigNumberish, studentDids: string[], leafIndices: BigNumberish[], ipfsCids: string[], ],
      [void],
      'nonpayable'
    >
    

    
    getBatch: TypedContractMethod<
      [batchId: string, ],
      [[string, bigint, bigint, boolean, boolean] & {merkleRoot: string, credentialCount: bigint, committedAt: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >
    

    
    getStudentCredentials: TypedContractMethod<
      [studentDid: string, ],
      [[string[], bigint[], string[]] & {batchIds: string[], leafIndices: bigint[], ipfsCids: string[] }],
      'view'
    >
    

    
    revokeCredential: TypedContractMethod<
      [credentialHash: BytesLike, batchId: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokedCredentials: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalBatches: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalCredentials: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    universityAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyCredential: TypedContractMethod<
      [batchId: string, credentialHash: BytesLike, proof: BytesLike[], leafIndex: BigNumberish, ],
      [[boolean, boolean, bigint] & {isValid: boolean, isRevoked: boolean, batchCommittedAt: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batchRoots'): TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'batches'): TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, bigint, boolean, boolean] & {merkleRoot: string, credentialCount: bigint, committedAt: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'commitBatch'): TypedContractMethod<
      [batchId: string, merkleRoot: BytesLike, credentialCount: BigNumberish, studentDids: string[], leafIndices: BigNumberish[], ipfsCids: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBatch'): TypedContractMethod<
      [batchId: string, ],
      [[string, bigint, bigint, boolean, boolean] & {merkleRoot: string, credentialCount: bigint, committedAt: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getStudentCredentials'): TypedContractMethod<
      [studentDid: string, ],
      [[string[], bigint[], string[]] & {batchIds: string[], leafIndices: bigint[], ipfsCids: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'revokeCredential'): TypedContractMethod<
      [credentialHash: BytesLike, batchId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokedCredentials'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalBatches'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalCredentials'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'universityAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyCredential'): TypedContractMethod<
      [batchId: string, credentialHash: BytesLike, proof: BytesLike[], leafIndex: BigNumberish, ],
      [[boolean, boolean, bigint] & {isValid: boolean, isRevoked: boolean, batchCommittedAt: bigint }],
      'view'
    >;

    getEvent(key: 'BatchCommitted'): TypedContractEvent<BatchCommittedEvent.InputTuple, BatchCommittedEvent.OutputTuple, BatchCommittedEvent.OutputObject>;
getEvent(key: 'BatchRevoked'): TypedContractEvent<BatchRevokedEvent.InputTuple, BatchRevokedEvent.OutputTuple, BatchRevokedEvent.OutputObject>;
getEvent(key: 'CredentialRevoked'): TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;

    filters: {
      
      'BatchCommitted(string,bytes32,uint256,address,uint256)': TypedContractEvent<BatchCommittedEvent.InputTuple, BatchCommittedEvent.OutputTuple, BatchCommittedEvent.OutputObject>;
      BatchCommitted: TypedContractEvent<BatchCommittedEvent.InputTuple, BatchCommittedEvent.OutputTuple, BatchCommittedEvent.OutputObject>;
    

      'BatchRevoked(string,address)': TypedContractEvent<BatchRevokedEvent.InputTuple, BatchRevokedEvent.OutputTuple, BatchRevokedEvent.OutputObject>;
      BatchRevoked: TypedContractEvent<BatchRevokedEvent.InputTuple, BatchRevokedEvent.OutputTuple, BatchRevokedEvent.OutputObject>;
    

      'CredentialRevoked(bytes32,string,address)': TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
      CredentialRevoked: TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
    
    };
  }